-libraryjars C:\WTK21\lib\midpapi20.jar;C:\WTK21\lib\wma.jar;C:\WTK21\lib\cldcapi10.jar;C:\WTK21\lib\mmapi.jar
-injars C:\WTK21\apps\Holi\bin\Holi.jar
-outjar C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\Holi.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
