-libraryjars C:\WTK21\lib\midpapi10.jar;C:\WTK21\lib\cldcapi10.jar
-injars C:\WTK21\apps\SKJ TicTacToe\bin\SKJ TicTacToe.jar
-outjar C:\DOCUME~1\SAURABH\LOCALS~1\Temp\SKJ TicTacToe.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
